"""add assigned_vendor_id to complaints

Revision ID: 965651cf9687
Revises: 0001
Create Date: 2026-03-29 21:39:33.820830

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '965651cf9687'
down_revision: Union[str, None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('attachments', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('audit_logs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.add_column('complaints', sa.Column('assigned_vendor_id', sa.Integer(), nullable=True))
    op.alter_column('complaints', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('complaints', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint('complaints_reference_id_key', 'complaints', type_='unique')
    op.drop_constraint('complaints_tracking_token_key', 'complaints', type_='unique')
    op.drop_index('ix_complaints_reference_id', table_name='complaints')
    op.create_index(op.f('ix_complaints_reference_id'), 'complaints', ['reference_id'], unique=True)
    op.drop_index('ix_complaints_tracking_token', table_name='complaints')
    op.create_index(op.f('ix_complaints_tracking_token'), 'complaints', ['tracking_token'], unique=True)
    op.create_foreign_key(None, 'complaints', 'users', ['assigned_vendor_id'], ['id'])
    op.alter_column('departments', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('replies', 'generated_by_ai',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('replies', 'loop_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('reports', 'generated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('sla_tracking', 'is_escalated',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint('users_email_key', 'users', type_='unique')
    op.drop_index('ix_users_email', table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.alter_column('vendor_attachments', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vendor_attachments', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index('ix_users_email', 'users', ['email'], unique=False)
    op.create_unique_constraint('users_email_key', 'users', ['email'])
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('sla_tracking', 'is_escalated',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('reports', 'generated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('replies', 'loop_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('replies', 'generated_by_ai',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('departments', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(None, 'complaints', type_='foreignkey')
    op.drop_index(op.f('ix_complaints_tracking_token'), table_name='complaints')
    op.create_index('ix_complaints_tracking_token', 'complaints', ['tracking_token'], unique=False)
    op.drop_index(op.f('ix_complaints_reference_id'), table_name='complaints')
    op.create_index('ix_complaints_reference_id', 'complaints', ['reference_id'], unique=False)
    op.create_unique_constraint('complaints_tracking_token_key', 'complaints', ['tracking_token'])
    op.create_unique_constraint('complaints_reference_id_key', 'complaints', ['reference_id'])
    op.alter_column('complaints', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('complaints', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_column('complaints', 'assigned_vendor_id')
    op.alter_column('audit_logs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('attachments', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###
